n = input('Digite algo: ')
print(type(n))
print('{} é numérico? {}'.format(n,n.isnumeric()))
print('{} é alfanumérico? {}'.format(n,n.isalnum()))
print('{} é alfabético? {}'.format(n,n.isalpha()))
print('{} está dentro do padrão ascii? {}'.format(n,n.isascii()))
print('{} possui dígitos? {}'.format(n,n.isdigit()))
print('{} é decimal? {}'.format(n,n.isdecimal()))
print('{} é um identificador? {}'.format(n,n.isidentifier()))
print('{} está em minúsculo? {}'.format(n,n.islower()))
print('{} está em maiúsculo? {}'.format(n,n.isupper()))
print('{} é exibível? {}'.format(n,n.isprintable()))
print('{} é um espaço? {}'.format(n,n.isspace()))
print('{} é um título? {}'.format(n,n.istitle()))

